version: "3"
networks:
  public:
    external: true

services:

  proxy:
    image: traefik:1.7
    command: "--docker --docker.endpoint='unix:///var/run/docker.sock' --docker.watch=true --docker.exposedByDefault=false --entryPoints='Name:http Address::80' --defaultEntryPoints='http' --accessLog --accessLog.filepath='/dev/stdout' --accessLog.format='common'"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
